# A sample Guardfile
# More info at https://github.com/guard/guard#readme


guard 'sass', input: 'sass', output: '../css'


guard 'sprockets', destination: 'js', asset_paths: ['coffee'] do
  watch(/coffee\/.*.js.coffee/) do
    'coffee/application.js.coffee'
  end
end
